// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-UG6Ah5x480lUaLXsIzEo9TOIzq1F70',
    appId: '1:1093409879663:ios:cea988a9a199bf62d6ff9a',
    messagingSenderId: '1093409879663',
    projectId: 'guvvy-45e04',
    storageBucket: 'guvvy-45e04.firebasestorage.app',
    iosBundleId: 'com.example.guvvy',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-UG6Ah5x480lUaLXsIzEo9TOIzq1F70',
    appId: '1:1093409879663:ios:cea988a9a199bf62d6ff9a',
    messagingSenderId: '1093409879663',
    projectId: 'guvvy-45e04',
    storageBucket: 'guvvy-45e04.firebasestorage.app',
    iosBundleId: 'com.example.guvvy',
  );
}
